a= input("Enter firstname :")
b=input("Enter lastname :")
c=input("Enter the DOB :")
d=input("Enter the city :")
e=input("Enter Address :")
f=int(input("Enter age : "))
g=int(input("Enter percentage :"))
h = input("Enter Department :")
i = input("Enter College Name :")
print(f"-------------STUDENT PROFILE-------------")
print(f"firstname :{a}")
print(f"lastname :{b}")
print(f"DOB :{c}")
print(f"City :{d}")
print(f"Address :{e}")
print(f"Age :{f}")
print(f"percentage :{g}")
print(f"Department :{h}")
print(f"Collegename :{i}")

input()